-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 21:08:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SCICONF
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SCICONF
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SCICONF` DEFAULT CHARACTER SET utf8 ;
USE `SCICONF` ;

-- -----------------------------------------------------
-- Table `SCICONF`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`country` (
  `idcountry` INT NOT NULL AUTO_INCREMENT,
  `iso_code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(300) NOT NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`university` (
  `iduniversity` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(20) NOT NULL,
  `name` VARCHAR(200) NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `country_idcountry` INT NOT NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  PRIMARY KEY (`iduniversity`),
  INDEX `fk_university_country1_idx` (`country_idcountry` ASC) VISIBLE,
  CONSTRAINT `fk_university_country1`
    FOREIGN KEY (`country_idcountry`)
    REFERENCES `SCICONF`.`country` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`faculty` (
  `idfaculty` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(20) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `university_iduniversity` INT NOT NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idfaculty`),
  INDEX `fk_faculty_university1_idx` (`university_iduniversity` ASC) VISIBLE,
  CONSTRAINT `fk_faculty_university1`
    FOREIGN KEY (`university_iduniversity`)
    REFERENCES `SCICONF`.`university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`department` (
  `iddepartment` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(20) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `faculty_idfaculty` INT NOT NULL,
  PRIMARY KEY (`iddepartment`),
  INDEX `fk_department_faculty1_idx` (`faculty_idfaculty` ASC) VISIBLE,
  CONSTRAINT `fk_department_faculty1`
    FOREIGN KEY (`faculty_idfaculty`)
    REFERENCES `SCICONF`.`faculty` (`idfaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(5) NOT NULL,
  `description` CHAR(20) NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `country_idcountry` INT NOT NULL,
  `department_iddepartment` INT NOT NULL,
  `role_idrole` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_country1_idx` (`country_idcountry` ASC) VISIBLE,
  INDEX `fk_user_department1_idx` (`department_iddepartment` ASC) VISIBLE,
  INDEX `fk_user_role1_idx` (`role_idrole` ASC) VISIBLE,
  CONSTRAINT `fk_user_country1`
    FOREIGN KEY (`country_idcountry`)
    REFERENCES `SCICONF`.`country` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_department1`
    FOREIGN KEY (`department_iddepartment`)
    REFERENCES `SCICONF`.`department` (`iddepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `SCICONF`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`review_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`review_status` (
  `idreview_status` INT NOT NULL AUTO_INCREMENT,
  `status` CHAR(2) NULL,
  `status_desc` VARCHAR(100) NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idreview_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`review` (
  `idreview` INT NOT NULL AUTO_INCREMENT,
  `grade1` CHAR(1) NULL,
  `grade2` CHAR(1) NULL,
  `grade3` CHAR(1) NULL,
  `grade4` CHAR(1) NULL,
  `grade5` CHAR(1) NULL,
  `grade6` CHAR(1) NULL,
  `grade7` CHAR(1) NULL,
  `grade8` CHAR(1) NULL,
  `grade9` CHAR(1) NULL,
  `grade10` CHAR(1) NULL,
  `yesno1` TINYINT NULL COMMENT 'Yes/no	',
  `yesno2` TINYINT NULL,
  `yesno3` TINYINT NULL,
  `yesno4` TINYINT NULL,
  `yesno5` TINYINT NULL,
  `yesno6` TINYINT NULL,
  `yesno7` TINYINT NULL,
  `yesno8` TINYINT NULL,
  `yesno9` TINYINT NULL,
  `yesno10` TINYINT NULL,
  `yesno11` TINYINT NULL,
  `yesno12` TINYINT NULL,
  `txt_plus` VARCHAR(500) NULL,
  `txt_minus` VARCHAR(500) NULL,
  `txt_general` VARCHAR(500) NULL,
  `review_status_idreview_status` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idreview`),
  INDEX `fk_review_review_status1_idx` (`review_status_idreview_status` ASC) VISIBLE,
  INDEX `fk_review_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_review_review_status1`
    FOREIGN KEY (`review_status_idreview_status`)
    REFERENCES `SCICONF`.`review_status` (`idreview_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `SCICONF`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`conference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`conference` (
  `idconference` INT NOT NULL AUTO_INCREMENT,
  `abbreviation` CHAR(30) NOT NULL,
  `submissions_from` DATETIME NULL,
  `submissions_to` DATETIME NULL,
  `take_place_from` DATE NULL,
  `take_place_to` DATE NULL,
  `description` VARCHAR(250) NULL,
  `country_idcountry` INT NOT NULL,
  `university_iduniversity` INT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idconference`),
  INDEX `fk_conference_country1_idx` (`country_idcountry` ASC) VISIBLE,
  INDEX `fk_conference_university1_idx` (`university_iduniversity` ASC) VISIBLE,
  CONSTRAINT `fk_conference_country1`
    FOREIGN KEY (`country_idcountry`)
    REFERENCES `SCICONF`.`country` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conference_university1`
    FOREIGN KEY (`university_iduniversity`)
    REFERENCES `SCICONF`.`university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`section` (
  `idsection` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idsection`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`paper` (
  `idpaper` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `path_filesystem` VARCHAR(500) NULL,
  `abstract_lang1` VARCHAR(1800) NULL,
  `abstract_lang2` VARCHAR(1800) NULL,
  `upload_datetime` DATETIME NULL,
  `reupload_datetime` DATETIME NULL,
  `keywords_lang1` VARCHAR(200) NULL,
  `keywords_lang2` VARCHAR(200) NULL,
  `status` CHAR(2) NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `review_idreview` INT NULL,
  `conference_idconference` INT NOT NULL,
  `section_idsection` INT NOT NULL,
  PRIMARY KEY (`idpaper`),
  INDEX `fk_paper_review1_idx` (`review_idreview` ASC) VISIBLE,
  INDEX `fk_paper_conference1_idx` (`conference_idconference` ASC) VISIBLE,
  INDEX `fk_paper_section1_idx` (`section_idsection` ASC) VISIBLE,
  CONSTRAINT `fk_paper_review1`
    FOREIGN KEY (`review_idreview`)
    REFERENCES `SCICONF`.`review` (`idreview`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paper_conference1`
    FOREIGN KEY (`conference_idconference`)
    REFERENCES `SCICONF`.`conference` (`idconference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paper_section1`
    FOREIGN KEY (`section_idsection`)
    REFERENCES `SCICONF`.`section` (`idsection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`user_has_paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`user_has_paper` (
  `user_iduser` INT NOT NULL,
  `paper_idpaper` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`user_iduser`, `paper_idpaper`),
  INDEX `fk_user_has_paper_paper1_idx` (`paper_idpaper` ASC) VISIBLE,
  INDEX `fk_user_has_paper_user_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_paper_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `SCICONF`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_paper_paper1`
    FOREIGN KEY (`paper_idpaper`)
    REFERENCES `SCICONF`.`paper` (`idpaper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`degree` (
  `iddegree` INT NOT NULL AUTO_INCREMENT,
  `abbreviation` VARCHAR(30) NOT NULL,
  `description` VARCHAR(150) NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`iddegree`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`permission` (
  `idpermission` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(5) NOT NULL,
  `description` CHAR(20) NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  PRIMARY KEY (`idpermission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`user_has_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`user_has_degree` (
  `user_iduser` INT NOT NULL,
  `degree_iddegree` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  PRIMARY KEY (`user_iduser`, `degree_iddegree`),
  INDEX `fk_user_has_degree_degree1_idx` (`degree_iddegree` ASC) VISIBLE,
  INDEX `fk_user_has_degree_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_degree_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `SCICONF`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_degree_degree1`
    FOREIGN KEY (`degree_iddegree`)
    REFERENCES `SCICONF`.`degree` (`iddegree`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`conference_has_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`conference_has_section` (
  `conference_idconference` INT NOT NULL,
  `section_idsection` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`conference_idconference`, `section_idsection`),
  INDEX `fk_conference_has_section_section1_idx` (`section_idsection` ASC) VISIBLE,
  INDEX `fk_conference_has_section_conference1_idx` (`conference_idconference` ASC) VISIBLE,
  CONSTRAINT `fk_conference_has_section_conference1`
    FOREIGN KEY (`conference_idconference`)
    REFERENCES `SCICONF`.`conference` (`idconference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conference_has_section_section1`
    FOREIGN KEY (`section_idsection`)
    REFERENCES `SCICONF`.`section` (`idsection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`conference_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`conference_has_user` (
  `conference_idconference` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`conference_idconference`, `user_iduser`),
  INDEX `fk_conference_has_user_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_conference_has_user_conference1_idx` (`conference_idconference` ASC) VISIBLE,
  CONSTRAINT `fk_conference_has_user_conference1`
    FOREIGN KEY (`conference_idconference`)
    REFERENCES `SCICONF`.`conference` (`idconference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conference_has_user_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `SCICONF`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`role_has_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`role_has_permission` (
  `role_idrole` INT NOT NULL,
  `permission_idpermission` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`role_idrole`, `permission_idpermission`),
  INDEX `fk_role_has_permission_permission1_idx` (`permission_idpermission` ASC) VISIBLE,
  INDEX `fk_role_has_permission_role1_idx` (`role_idrole` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `SCICONF`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_permission1`
    FOREIGN KEY (`permission_idpermission`)
    REFERENCES `SCICONF`.`permission` (`idpermission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
