-- MySQL Script generated by MySQL Workbench
-- Sat Jan  4 19:11:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SCICONF
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SCICONF
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SCICONF` DEFAULT CHARACTER SET utf8 ;
USE `SCICONF` ;

-- -----------------------------------------------------
-- Table `SCICONF`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`country` (
  `idcountry` INT NOT NULL AUTO_INCREMENT,
  `iso_code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(300) NOT NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`university` (
  `iduniversity` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(20) NOT NULL,
  `name` VARCHAR(200) NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `country_idcountry` INT NOT NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  PRIMARY KEY (`iduniversity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`faculty` (
  `idfaculty` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(20) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `university_iduniversity` INT NOT NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idfaculty`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`department` (
  `iddepartment` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(20) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `faculty_idfaculty` INT NOT NULL,
  PRIMARY KEY (`iddepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(5) NOT NULL,
  `description` CHAR(20) NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `email` VARCHAR(255) NULL,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(150) NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `country_idcountry` INT NOT NULL,
  `department_iddepartment` INT NOT NULL,
  `role_idrole` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`review_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`review_status` (
  `idreview_status` INT NOT NULL AUTO_INCREMENT,
  `status` CHAR(2) NULL,
  `status_desc` VARCHAR(100) NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idreview_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`review` (
  `idreview` INT NOT NULL AUTO_INCREMENT,
  `grade1` CHAR(1) NULL,
  `grade2` CHAR(1) NULL,
  `grade3` CHAR(1) NULL,
  `grade4` CHAR(1) NULL,
  `grade5` CHAR(1) NULL,
  `grade6` CHAR(1) NULL,
  `grade7` CHAR(1) NULL,
  `grade8` CHAR(1) NULL,
  `grade9` CHAR(1) NULL,
  `grade10` CHAR(1) NULL,
  `yesno1` TINYINT NULL COMMENT 'Yes/no	',
  `yesno2` TINYINT NULL,
  `yesno3` TINYINT NULL,
  `yesno4` TINYINT NULL,
  `yesno5` TINYINT NULL,
  `yesno6` TINYINT NULL,
  `yesno7` TINYINT NULL,
  `yesno8` TINYINT NULL,
  `yesno9` TINYINT NULL,
  `yesno10` TINYINT NULL,
  `yesno11` TINYINT NULL,
  `yesno12` TINYINT NULL,
  `txt_plus` VARCHAR(500) NULL,
  `txt_minus` VARCHAR(500) NULL,
  `txt_general` VARCHAR(500) NULL,
  `review_status_idreview_status` INT NULL,
  `user_iduser` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idreview`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`conference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`conference` (
  `idconference` INT NOT NULL AUTO_INCREMENT,
  `abbreviation` CHAR(30) NOT NULL,
  `submissions_from` DATETIME NULL,
  `submissions_to` DATETIME NULL,
  `take_place_from` DATE NULL,
  `take_place_to` DATE NULL,
  `description` VARCHAR(250) NULL,
  `country_idcountry` INT NULL,
  `university_iduniversity` INT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idconference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`section` (
  `idsection` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idsection`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`paper_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`paper_status` (
  `idpaper_status` INT NOT NULL AUTO_INCREMENT,
  `status` CHAR(2) NOT NULL,
  `status_desc` VARCHAR(100) NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`idpaper_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`paper` (
  `idpaper` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `path_filesystem_doc` VARCHAR(500) NULL,
  `path_filesystem_pdf` VARCHAR(500) NULL,
  `pdf_filename` VARCHAR(100) NULL,
  `doc_filename` VARCHAR(100) NULL,
  `abstract_lang1` VARCHAR(1800) NULL,
  `abstract_lang2` VARCHAR(1800) NULL,
  `upload_datetime` DATETIME NULL,
  `reupload_datetime` DATETIME NULL,
  `keywords_lang1` VARCHAR(200) NULL,
  `keywords_lang2` VARCHAR(200) NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `review_idreview` INT NULL,
  `conference_idconference` INT NOT NULL,
  `section_idsection` INT NOT NULL,
  `paper_status_idpaper_status` INT NOT NULL,
  PRIMARY KEY (`idpaper`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`user_has_paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`user_has_paper` (
  `user_iduser` INT NOT NULL,
  `paper_idpaper` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`user_iduser`, `paper_idpaper`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`degree` (
  `iddegree` INT NOT NULL AUTO_INCREMENT,
  `abbreviation` VARCHAR(30) NOT NULL,
  `description` VARCHAR(150) NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`iddegree`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`permission` (
  `idpermission` INT NOT NULL AUTO_INCREMENT,
  `code` CHAR(5) NOT NULL,
  `description` CHAR(20) NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  PRIMARY KEY (`idpermission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`user_has_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`user_has_degree` (
  `user_iduser` INT NOT NULL,
  `degree_iddegree` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  PRIMARY KEY (`user_iduser`, `degree_iddegree`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`conference_has_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`conference_has_section` (
  `conference_idconference` INT NOT NULL,
  `section_idsection` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`conference_idconference`, `section_idsection`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`conference_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`conference_has_user` (
  `conference_idconference` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`conference_idconference`, `user_iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCICONF`.`role_has_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCICONF`.`role_has_permission` (
  `role_idrole` INT NOT NULL,
  `permission_idpermission` INT NOT NULL,
  `created_on` TIMESTAMP NULL,
  `updated_on` TIMESTAMP NULL,
  PRIMARY KEY (`role_idrole`, `permission_idpermission`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
